# task config
task: heading

# simulation config
jsbsim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 900              # episode: 180s
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.0,
      ic_lat_geod_deg: 60.0,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
      heading_check_time: 20.0,
    }
  }
}
# (lontitude, latitude, altitude)
battle_field_center: [120.0, 60.0, 0.0]

# reward config
AltitudeReward_safe_altitude: 4.0
AltitudeReward_danger_altitude: 3.5
AltitudeReward_Kv: 0.2
